### ISSUE TITLE
Need Support for Svelte Framework

### ISSUE THREAD

**Issue by ssantanuberaa** [marcelodolza/iziToast#205]
Hello IZI Team,
I cannot use sweet iziToast in my Svelte project.

```
✔ service worker (10ms)
webpack:///./node_modules/izitoast/dist/js/iziToast.js?:22
                BODY = document.querySelector('body'),
                       ^

ReferenceError: document is not defined
    at eval (webpack:///./node_modules/izitoast/dist/js/iziToast.js?:22:10)
    at eval (webpack:///./node_modules/izitoast/dist/js/iziToast.js?:8:74)
    at eval (webpack:///./node_modules/izitoast/dist/js/iziToast.js?:13:3)
    at Object../node_modules/izitoast/dist/js/iziToast.js (C:\repos\competitive\__sapper__\dev\server\server.js:97:1)
    at __webpack_require__ (C:\repos\competitive\__sapper__\dev\server\server.js:21:30)
    at eval (webpack:///./src/routes/index.svelte?:7:66)
    at Module../src/routes/index.svelte (C:\repos\competitive\__sapper__\dev\server\server.js:349:1)
    at __webpack_require__ (C:\repos\competitive\__sapper__\dev\server\server.js:21:30)
    at eval (webpack:///./src/node_modules/@sapper/internal/manifest-server.mjs?:8:78)
    at Module../src/node_modules/@sapper/internal/manifest-server.mjs (C:\repos\competitive\__sapper__\dev\server\server.js:205:1)
> Server crashed
```

**Comment by Nisthar** [comment]
try checking if its running on the browser
